### ISSUE TITLE
Can't reset password

### ISSUE THREAD

**Issue by kimdvm** [Ariel-Thomas/adventurers-league-log#231] opened 2019-07-09 13:35 UTC
I'm trying to reset my password.  I keep getting ERR_CONNECTION_TIMED_OUT message.  I tried several browsers and devices with no luck.

**Comment by devnuhl** [comment] 2019-07-22 15:11
Duplicate of #184 
Work around is there. ([quick link](https://github.com/Ariel-Thomas/adventurers-league-log/issues/184#issuecomment-489213851))

**Comment by kimdvm** [comment] 2019-07-22 17:54
Thank you.

**Comment by Ariel-Thomas** [comment] 2019-08-03 20:51
Thanks for the report.

Fixed in PR #226

**Closed by Ariel-Thomas** 2019-08-03 20:51 UTC
