### ISSUE TITLE
Bug: Magic Items added via DM Log entries no longer appear in list or count

### ISSUE THREAD

**Issue by kenibrewer** [Ariel-Thomas/adventurers-league-log#73] opened 2017-04-01 16:20 UTC
Since the magic item updates, when assigning magic items to characters via DM log entries, they no longer appear in the character's count or list of magic items. Items added via DM log prior to the update appear to be unaffected. Only new magic items appear to be affected.

**Comment by xanstin** [comment] 2017-04-01 17:18
![example](https://cloud.githubusercontent.com/assets/26841771/24580835/99a86fb2-16dd-11e7-9ed2-e02aa0ae6f6a.png)
Seems like its not taking the Assigned PC. In the edit mode it shows its assigning but when you preview it doesn't show the assigned PC.

**Comment by Ariel-Thomas** [comment] 2017-04-01 18:29
Crap. I totally forgot about this functionality. Good to hear things made the jump.  At a convention, but working on a fix.

**Comment by Ariel-Thomas** [comment] 2017-04-01 19:24
Hopefully the issue is fixed now. Let me know.

**Closed by Ariel-Thomas** 2017-04-01 19:24 UTC
Labels: bug
