### ISSUE TITLE
Gold

### ISSUE THREAD

**Issue by mortalis7** [Ariel-Thomas/adventurers-league-log#207] opened 2018-11-08 05:08 UTC
So it seems that every first level character I put on the logs is being given 75 gold at level one which as far as I know is not the case in session 8 of AL....

**Comment by tjclayton** [comment] 2018-11-08 13:41
I may not be understanding what you are saying, but if you are talking about going from level 1 to level 2 with 4 ACP, you get 75 gold. If it is just creating a character with 0 ACP, I do not get 75 gold until the character hits level 2 when I test the site. Maybe a screenshot would help to troubleshoot?

I hope that helps.

**Comment by mortalis7** [comment] 2018-11-08 16:52
Yes your correct. But what I’m seeing ever time I start a new character log in the app is a lvl 1 character starting with 75 gold which it should not. They should only have what there starting fear gave them, which also brings up the fact that I can not manually enter there starting gold. Also there is no way to track when and if gold is spent that I can see.

Sent from my iPhone

> On Nov 8, 2018, at 7:41 AM, tjclayton <notifications@github.com> wrote:
> 
> I may not be understanding what you are saying, but if you are talking about going from level 1 to level 2 with 4 ACP, you get 75 gold. If it is just creating a character with 0 ACP, I do not get 75 gold until the character hits level 2 when I test the site. Maybe a screenshot would help to troubleshoot?
> 
> I hope that helps.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
____________________________________________________________
We Say Goodbye To Kathie Lee Gifford
track.volutrk.com
http://thirdpartyoffers.netzero.net/TGL3231/5be469d83de4069d77d50st03duc

**Comment by tjclayton** [comment] 2018-11-08 17:03
Hmmm... OK. I don't see that behavior.

For starting gold I typically create an entry that has those details. Then when you add entries you can specify +/- gold.

**Comment by mortalis7** [comment] 2018-11-08 19:16
Ok I will double check with a new character and see if it happens again. It has happened twice to me so far... could be something on my end. Thank you for your time. Sorry if this is all basic but I’m new to AL and still learning it all. 

Sent from my iPhone

> On Nov 8, 2018, at 11:03 AM, tjclayton <notifications@github.com> wrote:
> 
> Hmmm... OK. I don't see that behavior.
> 
> For starting gold I typically create an entry that has those details. Then when you add entries you can specify +/- gold.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
____________________________________________________________
How To Remove Eye Bags & Lip Lines Fast (Watch)
ourhealthpros.com
http://thirdpartyoffers.netzero.net/TGL3231/5be48b6973ddb685d86st03vuc

**Comment by sorce-mage** [comment] 2019-01-05 15:16
When a Tier 3 character levels up, it's adding 559 gp, rather than 550 gp.

**Comment by devnuhl** [comment] 2019-05-03 19:31
Cannot reproduce 75 gold at level 1. Does not seem possible in code. Are you using/setting XP and Checkpoints for some reason?

Submitted PR for 559gp at T3.

**Comment by KnightCa** [comment] 2019-06-18 18:07
There is a mismatch in gold when gaining enough ACP to level on the Character Page versus the printed Log Sheet.

It records the correct gold increase on the Character page (Total GP), but when you go to Print either type of Logs (Full or Condensed), the leveling GP doesn't show up. 

If you make sure the log sheet is correct by entering the leveling GP on the Game Log Entry, then the log sheet is correct, but the Character page Total GP is incorrect.

Steps to Reproduce:
1. Create new character
2. Add a Reward with 4 ACP (enough to level to 2)
3. Verify that the Character Page shows a Total GP of 75. Try to print the log sheet and notice that the GP entry doesn't have the 75 gp.

**Comment by ADubhlaoich** [comment] 2019-06-23 17:07
I'm running into a similar issue - my character's background starts them out with 10 gold. 

I've brought them on their first adventure, and added 75 gold from their level up (1 > 2).

Subsequently, their character sheet lists them as having 150 gold.

I've "fixed" this by pretending I didn't get 75 gold from my level up in my single log, but this makes the auditing inaccurate.

**Comment by KnightCa** [comment] 2019-06-23 17:19
> I'm running into a similar issue - my character's background starts them out with 10 gold.
> 
> I've brought them on their first adventure, and added 75 gold from their level up (1 > 2).
> 
> Subsequently, their character sheet lists them as having 150 gold.
> 
> I've "fixed" this by pretending I didn't get 75 gold from my level up in my single log, but this makes the auditing inaccurate.

You can assign them the 75gp in the game log entry, then use the print feature to check the logs for auditing. They should be correct there.

**Comment by ADubhlaoich** [comment] 2019-06-23 23:06
> You can assign them the 75gp in the game log entry, then use the print feature to check the logs for auditing. They should be correct there.

This works fine for showing it off to other people, but it still doesn't address the 75 gold that a new character seems to arbitrarily start with. It could be fixed with a 'Starting Gold' field in character details that can be manually input, but otherwise this does seem like a bug.

(https://www.adventurersleaguelog.com/users/16954/characters/42549)[Here's the character in question], with the visibly incorrect 150 gold.

**Comment by ADubhlaoich** [comment] 2019-06-25 18:20
Upon farther investigation, I've realised that an issue is that it implicitly includes the gold from leveling up - but there's no text/explanation suggesting this from a new entry. This means if you get enough ACP to level up in tier 1 and also add 75 in the entry unaware of this, your character will be marked with +150 gold instead of +75.

This still doesn't account for the fact you can start with a variable amount of gold based on your background, however.

**Closed** 2019-08-03 21:18 UTC
