### ISSUE TITLE
Unable to recover password

### ISSUE THREAD

**Issue by Greglando** [Ariel-Thomas/adventurers-league-log#218] opened 2019-02-26 17:51 UTC
Hello everybody.

After formatting my PC, I was unable to recover my Account Password.
I recive the email to change it, but when I click on the link to "Change my password" the connection goes timeout after a while.

I tried to contact you with FB Messenger, but nobody answered, so I had to sign in with Gith Hub.

Please help me.

Best regards, 
Giovanni.

**Comment by kinghskac** [comment] 2019-03-08 18:01
I too am having the same issue.

**Comment by devnuhl** [comment] 2019-05-13 19:38
This is a duplicate of #184 and can be easily resolved if you simply add "www." before https://adventurersleaguelog.com.

There is currently a PR to solve this but the above will work anytime you need to change your password until that is merged into the code.

**Closed** 2019-08-03 21:05 UTC
