### ISSUE TITLE
Suggestion: Have Campaign Log Entries Update DM Logs

### ISSUE THREAD

**Issue by Sansd20** [Ariel-Thomas/adventurers-league-log#91] opened 2017-07-21 18:42 UTC
As it stands, when I DM, I have to add a log to the Campaign and then go over and add to the DM Logs. 

I would like to see when I would only have to add a campaign log entry and it would automatically update the DM Logs. Enter the info in once.

**Comment by Sansd20** [comment] 2017-07-21 19:11
Just noticed that this could be the same as [Add Mirrored DM Log Entry for Campaign Log Entries. #66](https://github.com/Ariel-Thomas/adventurers-league-log/issues/66)

**Comment by Ariel-Thomas** [comment] 2017-08-12 09:38
Yeah, this is a dupe of #66

**Closed by Ariel-Thomas** 2017-08-12 09:38 UTC
Labels: duplicate
